# Uncomment the next line to define a global platform for your project
 platform :watchos, '6.0'

target 'PC-Watch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PC-Watch

end

target 'PC-Watch WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PC-Watch WatchKit App

end

target 'PC-Watch WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PC-Watch WatchKit Extension

  pod 'FirebaseCore'
  pod 'GoogleUtilities'
  pod 'FirebaseMessaging'
  pod 'FirebaseInstanceID'
  pod 'FirebaseCoreDiagnostics'
  pod 'GoogleDataTransport'
  pod 'FirebaseInstallations'
  pod 'FirebaseStorage'
  pod 'SwiftSoup'

end

#target 'ServiceExtension' do
# pod 'FirebaseMessaging'
# pod 'FirebaseInstanceID'
#end

